//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHF.Business.Models.RHF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Member> T_Member { get; set; }
        public DbSet<T_LoginLog> T_LoginLog { get; set; }
        public DbSet<T_Book> T_Book { get; set; }
        public DbSet<M_BookCategory> M_BookCategory { get; set; }
        public DbSet<R_BookCategory> R_BookCategory { get; set; }
    }
}
