//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHF.Business.Models.RHF
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_BookCategory
    {
        public long ID { get; set; }
        public long BookID { get; set; }
        public int BookCategoryID { get; set; }
    }
}
