//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHF.Business.Models.RHF
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Book
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long MemberID { get; set; }
        public string Image { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
